name: Publish Web

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email leonardobenedeti@gmail.com
          git config --global user.name leonardobenedeti
          git status
          git remote add origin https://${{secrets.TOKEN_FOR_BUILD}}@github.com/leonardobenedeti/appinstaller.git
          git checkout -b production
          git add --all
          git commit -m "Publish by Actions"
          git push origin production -f
